ProtocolConfiguration:
  Magic: 56753
  MaxTraceableBlocks: 200000
  SecondsPerBlock: 15
  MemPoolSize: 50000
  StandbyCommittee:
    - 02b3622bf4017bdfe317c58aed5f4c753f206b7db896046fa7d774bbc4bf7f8dc2
    - 02103a7f7dd016558597f7960d27c516a4394fd968b9e65155eb4b013e4040406e
    - 03d90c07df63e690ce77912e10ab51acc944b66860237b608c4f8f8309e71ee699
    - 02a7bc55fe8684e0119768d104ba30795bdcc86619e864add26156723ed185cd62
  ValidatorsCount: 4
  SeedList:
    - node_one:20333
    - node_two:20334
    - node_three:20335
    - node_four:20336
  VerifyBlocks: true
  VerifyTransactions: true
  P2PSigExtensions: false
  NativeActivations:
    ContractManagement: [0]
    StdLib: [0]
    CryptoLib: [0]
    LedgerContract: [0]
    NeoToken: [0]
    GasToken: [0]
    PolicyContract: [0]
    RoleManagement: [0]
    OracleContract: [0]

ApplicationConfiguration:
  # LogPath could be set up in case you need stdout logs to some proper file.
  # LogPath: "./log/neogo.log"
  DBConfiguration:
    Type: "leveldb" #other options: 'inmemory','boltdb'
    # DB type options. Uncomment those you need in case you want to switch DB type.
    LevelDBOptions:
      DataDirectoryPath: "/chains/one"
  #    BoltDBOptions:
  #      FilePath: "./chains/privnet.bolt"
  #  Uncomment in order to set up custom address for node.
  #  Address: 127.0.0.1
  NodePort: 20333
  Relay: true
  DialTimeout: 3
  ProtoTickInterval: 2
  PingInterval: 30
  PingTimeout: 90
  MaxPeers: 10
  AttemptConnPeers: 5
  MinPeers: 3
  Oracle:
    Enabled: false
    AllowedContentTypes:
      - application/json
    Nodes:
      - http://node_one:30333
      - http://node_two:30334
      - http://node_three:30335
      - http://node_four:30336
    RequestTimeout: 5s
    UnlockWallet:
      Path: "/wallet1.json"
      Password: "one"
  P2PNotary:
    Enabled: false
    UnlockWallet:
      Path: "/notary_wallet.json"
      Password: "pass"
  RPC:
    Enabled: true
    MaxGasInvoke: 15
    EnableCORSWorkaround: false
    Port: 30333
  Prometheus:
    Enabled: true
    Port: 20001
  Pprof:
    Enabled: false
    Port: 20011
  UnlockWallet:
    Path: "/wallet1.json"
    Password: "one"
