language: go
go:
  - 1.15.x
env:
  - GO111MODULE=on
install:
  - go get -v golang.org/x/lint/golint
  - go mod tidy -v
script:
  - golint -set_exit_status ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./pkg/...,./cli/... ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
matrix:
  allow_failures:
    - go: tip
