# Database credentials
#database_dev:
#  host: "s-uf63bd0cc5896674-pub.mongodb.rds.aliyuncs.com"
#  port: "3717"
#  user: "Vincent"
#  pass: "QMRhLk9m8rqXWC3X9pMJ"
#  dbname: "neofura"
#  database: "neofura"
database_main:
  host: "localhost"
  port: "27017"
  user: "Guru99"
  pass: "password"
  dbname: "test"
  database: "test"

database_test:
  host: "localhost"
  port: "27017"
  user: "Guru99"
  pass: "password"
  dbname: "test"
  database: "test"